name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@latest
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false # Disable automatic install to control it manually

      - name: Install dependencies
        run: pnpm install # Explicitly run pnpm install

      - name: Run ESLint
        run: pnpm lint

  test:
    name: Test (placeholder)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false # Disable automatic install

      - name: Install dependencies
        run: pnpm install # Explicitly run pnpm install

      - name: Run Tests (placeholder)
        run: echo "No tests yet" # Replace with `pnpm test` later

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false # Disable automatic install

      - name: Install dependencies
        run: pnpm install # Explicitly run pnpm install

      - name: Build project
        run: pnpm build